name: weather_app
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ^3.7.0


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  fluttertoast: ^8.2.12


  # core
  internet_connection_checker_plus: ^2.7.1


  #API
  dio: ^5.8.0+1
  pretty_dio_logger: ^1.4.0

  #UI
  flutter_svg: ^2.0.17
  animations: ^2.0.11
  smooth_page_indicator: ^1.2.1
  skeletonizer: ^1.4.3
  cached_network_image: ^3.4.1

  #others
  flutter_bloc: ^9.1.0 #state management
  get_it: ^8.0.3 #dependency injection

  intl: ^0.19.0 #Format date

  

  go_router: ^14.8.1
  event_bus: ^2.0.1
  flutter_dotenv: ^5.2.1



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0




# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/svg/
    - assets/png/
    - assets/.env
  
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
flutter_assets:
  assets_path: assets/
  output_path: lib/core/resources/
  filename: assets.dart
